[dns_dhcp_servers]
# Descomentar para producción y cambiar IP:
# prod-server ansible_host=192.168.100.10 ansible_user=rocky

[rocky]
# Entorno de pruebas Docker
rocky9-test ansible_connection=docker ansible_user=root

[all:children]
dns_dhcp_servers
rocky